config/routes.rb
Rails.application.routes.draw do
  
  resources :majors
  resources :courses
  resources :departments
  resources :colleges
  get 'pages/index'

  
  devise_for :users

  
  resources :appointments do
    resources :notes
  end

  resources :users#, :except => [:create, :new]

  resources :users do
    resources :appointments do    
      collection do
        get 'agenda'
      end
    end
    resources :degree_progressions
    member do
      get 'edit_student', :to => "users#edit_student"
    end
  end
  
  root to: "pages#index"

  # need to remove this
  resources :notes
  resources :degree_progressions
  
end

app/models/major.rb
class Major < ActiveRecord::Base
  belongs_to :department
  has_one :user
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(:name, :department_id)
    end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_form.html.erb
<%= form_for(@major) do |f| %>
  <% if @major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
      <% @major.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.text_field :department_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/majors/edit.html.erb
<h1>Editing Major</h1>

<%= render 'form' %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Majors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td><%= major.name %></td>
        <td><%= major.department %></td>
        <td><%= link_to 'Show', major %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path %>

app/views/majors/new.html.erb
<h1>New Major</h1>

<%= render 'form' %>

<%= link_to 'Back', majors_path %>

app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @major.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @major.department %>
</p>

<%= link_to 'Edit', edit_major_path(@major) %> |
<%= link_to 'Back', majors_path %>