config/routes.rb
Rails.application.routes.draw do
  
  resources :majors
  resources :courses
  resources :departments
  resources :colleges
  get 'pages/index'

  
  devise_for :users

  
  resources :appointments do
    resources :notes
  end

  resources :users#, :except => [:create, :new]

  resources :users do
    resources :appointments do    
      collection do
        get 'agenda'
      end
    end
    resources :degree_progressions
    member do
      get 'edit_student', :to => "users#edit_student"
    end
  end
  
  root to: "pages#index"

  # need to remove this
  resources :notes
  resources :degree_progressions
  
end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :departments
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>