config/routes.rb
Rails.application.routes.draw do
  
  resources :majors
  resources :courses
  resources :departments
  resources :colleges
  get 'pages/index'

  
  devise_for :users

  
  resources :appointments do
    resources :notes
  end

  resources :users#, :except => [:create, :new]

  resources :users do
    resources :appointments do    
      collection do
        get 'agenda'
      end
    end
    resources :degree_progressions
    member do
      get 'edit_student', :to => "users#edit_student"
    end
  end
  
  root to: "pages#index"

  # need to remove this
  resources :notes
  resources :degree_progressions
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :advisor, :class_name => 'User', :foreign_key => 'advisor_id'
  belongs_to :student, :class_name => 'User', :foreign_key => 'student_id'
  
  belongs_to :note

  after_save :check_note
  before_save :update_end_time
  
  validates :advisor_id, presence: true
  validates :student_id, presence: true

  
  
  private
  def check_note
    # st = self.start_time
    # self.update_attributes(:end_time => st + 30*60)
    
    if self.note.nil?
      _note = Note.create
      self.update_attributes(:note => _note)
    end

    # only send an email if the start time has changed
    if start_time_changed?
      UserMailer.appointment_notification_email(self.student, self).deliver_now
      UserMailer.appointment_notification_email_to_advisor(self.advisor, self).deliver_now
    end
  end

  def update_end_time
    self.end_time = self.start_time + 60*30
  end
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  authorize_resource

  def index
    @appointments = current_user.appointments_advisor
  end

  def agenda
    # this is only available to advisors
    @appointments = current_user.appointments_student
  end

  def show
  end


  def new
    @appointment = current_user.appointments_advisor.new
  end


  def edit
  end


  def create
    
    # create a new appointment with advisor
    @appointment = current_user.appointments_advisor.new(appointment_params)
    @appointment.student_id = current_user.id
    
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to current_user, notice: 'Successfully created appointment' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to current_user, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:student_id,
                                          :user_id,
                                          :advisor_id,
                                          :advisor,
                                          :start_time,
                                          :end_time,
                                          :note)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%#
we could have also supplied a url by:
url: url_for(controller: 'appointments', action: 'create')
%>

<div class="col-md-6 col-md-offset-3">
  <%= form_for([@current_user, @appointment ], {:class => "form"}) do |f| %>
    
    <% if @appointment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this course from being saved:</h2>

        <ul>
          <% @appointment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- <div class="field">
         <%#= f.label :note %><br>
         <%#= f.text_field :note_id %>
         </div> -->
    
    <div class="form-group">
      <%= f.label :advisor %>
      <%= f.collection_select :advisor_id, User.get_advisors, :id, :first_name, {}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.datetime_select :start_time %>
    </div>


    <div class="actions">
      <%= f.submit "Submit", :class => "btn" %>
    </div>
  <% end %>

</div>

app/views/appointments/agenda.html.erb
<h1>Todays Appointments</h1>

<table class="table table-striped">

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= link_to appointment.student.first_name, user_path(appointment.student) %></td>
        <td><%= appointment.start_time.to_date %> at <%= appointment.start_time.to_s(:time) %></td>
        <td><%= link_to "Notes", edit_appointment_note_path(:appointment_id => appointment.id, :id => appointment.note.id), {:class => "btn btn-success"} %></td>
       
        <td><%= link_to "Degree plan", user_degree_progressions_path(:user_id => appointment.student.id), {:class => "btn btn-success"} %></td>
        <td><%= link_to "Major", edit_student_user_path(appointment.student.id), {:class => "btn btn-success"} %></td>
         <td><%= link_to "Previous Advisor's Notes", notes_path(:id => appointment.note.id), {:class => "btn btn-success"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<table class="table table-striped">

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= link_to appointment.advisor.first_name, user_path(appointment.advisor) %></td>
        <td><%= appointment.start_time.to_date %> at <%= appointment.start_time.to_s(:time) %></td>
        <% if appointment.note.nil? %>
          <td><em>No notes yet!</em></td>
        <% else %>
          <td><%= link_to "Notes", appointment_note_path(:appointment_id => appointment.id, :id => appointment.note.id) %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
<%= link_to 'New Appointment', new_user_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Credit:</strong>
  <%= @appointment.student_id %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @appointment.user_id %>
</p>

<%= link_to 'Edit', edit_user_appointment_path(@appointment) %> |