config/routes.rb
Rails.application.routes.draw do
  
  resources :majors
  resources :courses
  resources :departments
  resources :colleges
  get 'pages/index'

  
  devise_for :users

  
  resources :appointments do
    resources :notes
  end

  resources :users#, :except => [:create, :new]

  resources :users do
    resources :appointments do    
      collection do
        get 'agenda'
      end
    end
    resources :degree_progressions
    member do
      get 'edit_student', :to => "users#edit_student"
    end
  end
  
  root to: "pages#index"

  # need to remove this
  resources :notes
  resources :degree_progressions
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.roles.include?(Role.find_by(:name => "Advisor"))
      can :manage, :all
      can :agenda, Appointment
    else
      can :read, DegreeProgression
      can :manage, Appointment
      can :manage, User
      cannot :agenda, Appointment
      cannot :create, Note
      cannot :update_student, User
      can :read, Note
    end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :advisor, :class_name => 'User', :foreign_key => 'advisor_id'
  belongs_to :student, :class_name => 'User', :foreign_key => 'student_id'
  
  belongs_to :note

  after_save :check_note
  before_save :update_end_time
  
  validates :advisor_id, presence: true
  validates :student_id, presence: true

  
  
  private
  def check_note
    # st = self.start_time
    # self.update_attributes(:end_time => st + 30*60)
    
    if self.note.nil?
      _note = Note.create
      self.update_attributes(:note => _note)
    end

    # only send an email if the start time has changed
    if start_time_changed?
      UserMailer.appointment_notification_email(self.student, self).deliver_now
      UserMailer.appointment_notification_email_to_advisor(self.advisor, self).deliver_now
    end
  end

  def update_end_time
    self.end_time = self.start_time + 60*30
  end
  
end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :departments
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :department
end

app/models/degree_progression.rb
class DegreeProgression < ActiveRecord::Base
  belongs_to :students,
             :class_name => 'User',
             :foreign_key => 'user_id'
  
  belongs_to :course
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :college
  has_many :majors
  
end

app/models/major.rb
class Major < ActiveRecord::Base
  belongs_to :department
  has_one :user
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_one :appointment
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :cas_authenticatable, :trackable
  has_and_belongs_to_many :roles
  belongs_to :department

  # TODO support for dual majors
  belongs_to :major
  
  has_many :appointments_advisor,
           :class_name => 'Appointment',
           :foreign_key => 'student_id'
  
  has_many :appointments_student,
           :class_name => 'Appointment',
           :foreign_key => 'advisor_id'

  
  validates :username, presence: true
  validates :email, presence: true
  validates :role_ids, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :courses,
           :class_name => "DegreeProgression",
           :foreign_key => "user_id"

  after_save :check_student_major

  def self.get_advisors
    role = Role.find_by(:name =>"Advisor")
    # User.where(role_id: role.id).all
    User.joins(:roles).where("roles_users.role_id is #{role.id}")
  end
  
  

  # Get open times. Queries the appointments table to retrieve
  # time slots available for a given user Assume you want times from 8-5 M-F.
  # 
  # Returns a list of times in the form of Time objects (for now).
  #
  def self.get_availablities(advisor_id, start_t, end_t)

    if Appointment.find_by(user_id=advisor_id).nil?
      "free"
    else
      Appointment.find_by(user_id=advisor_id)
      # [Time.utc(2015,11,17,8,15)]
    end
  end

  private
  def check_student_major
    if self.roles.exists?(:name => "Student") && self.major.nil?
      _major = Major.find_by(:name => "Undeclared")
      self.update_attributes(:major => _major)
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:advisor_notes, :advisor_student_notes)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Advisement</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <nav id="header" class="navbar navbar-fixed-top">
      <div id="header-container" class="container navbar-container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
          </button>
          <a id="brand" class="navbar-brand" href="<%= root_path %>">Advisement</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if !current_user.nil? %>
              <li><%= link_to "Log out",destroy_user_session_path, :method=>'delete', :id => "Logout" %></li>
          </ul> 
          <ul class="nav navbar-nav pull-right">
            <li> <%= link_to current_user.first_name, edit_user_path(current_user) %> </li>
            <% if  current_user.roles.exists?(:name => "Advisor") %>
              <li> <%= link_to "Advise", agenda_user_appointments_path(current_user) %> </li>
            <% elsif current_user.roles.exists?(:name =>"Student")%>
              <li> <%= link_to "Student", user_appointments_path(current_user) %> </li>
              <li> <%= link_to "My progress", user_degree_progressions_path(current_user) %> </li>
            <% end %>
          </ul>
            <% else %>
          <ul class="nav navbar-nav pull-right">
            <li> <%= link_to 'Login', new_user_session_path %> </li>
            <li> <%= link_to 'Sign up', new_user_path %> </li>
          </ul>
            <% end %>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    
    <div class="container-fluid">

      <div class="bg"></div>
      
      <div id="card" class="container">
        <div class="page-header">
          <h1><%#= raw title %></h1>
        </div>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        
        <div class="container-fluid">
          <%= yield %>
        </div>
        <hr>
      </div>
      
      <script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  </body>
</html> 

app/views/pages/index.html.erb
<%= image_tag("unm-flagship-logo.png", :class => "banner-logo") %>
<!-- <h1>Advisement Home</h1> -->

<% if !current_user.nil? %>

<% end %>

<div class="container">
<%= image_tag("graduation-2015.jpg") %>

<div id="home-groups">
    <div class="home-group">
        <h2>News</h2>
        <hr>
        
        <div class="panel-item">
            <a href="http://localhost:3000/" class="panel-title">Advisement Web Application Complete</a>
            <p class="panel-date">December 9, 2015</p>
        </div>
    </div>
    <div class="home-group">
        <h2>Events</h2>
        <hr>
        <div class="panel-item">
            <a href="http://localhost:3000/" class="panel-title">Advisement Web Application Complete</a>
            <p class="panel-date">December 9, 2015</p>
        </div>
    </div>
</div>